### ISSUE TITLE
Version 2.0.4 of the Select plugin is released

### ISSUE THREAD

**Issue by dagframstad** [webjars/datatables-select#6]
Any chance of automating this with dependabot or something?

**Comment by jamesward** [comment]
There may be a way to automate this in the future but the first step will be to migrate this WebJar to the new Classic setup: https://github.com/webjars/webjars-classic
Then this WebJar will be user deployable. I need to make some https://github.com/webjars/webjars changes to enable that first.

**Comment by jamesward** [comment]
This WebJar is now user-deployable via https://webjars.org - let me know if you have any issues.  Thanks!
